### ISSUE TITLE
Improve QOA gapless playback

### ISSUE THREAD

**Issue by sergeevabc** [braheezy/goqoa#12]
Windows 7 x64, Foobar2000 2.1 with foo_qoa decoder 0.3.0, goqoa 2.0.0

Source:  [download.zip](https://github.com/braheezy/goqoa/files/14330355/Improve.QOA.gapless.playback.2024a.zip) (1 972 678  bytes)

* 15s continuous music sample 44.1kHz cut into 10s and 5s FLAC pieces
* QOA encoded pieces are played via WASAPI Shared without DSP
* there is a click between the pieces, which is not as audible as in the case of Opus, but still noticeable against the background of Musepack and Vorbis

cc: @phoboslab, @pfusik

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by braheezy** [comment]
Hello! Apologies for the delay, I've been moving and without proper Internet access.

Could clarify the role `goqoa` played here? Did you use it for encoding, playing, etc. 

And have you experienced the bug with other implementations of the QOA format?

**Comment by sergeevabc** [comment]
Goqua is one of the two QOA encoders that I was able to find in a binary form suitable for Windows 7 x64. The [second one](https://hydrogenaud.io/index.php/topic,123838.msg1026084.html#msg1026084) was shared by the author of the Rarewares project on Hydrogenaudio forum.

In both cases, the output files are the same size. However, the second encoder takes up 10 times less space (~250 KB) and is more informative as follows

``` console
$ qoaconvert.exe original01.flac encoded01.qoa
original01.flac: channels: 2, samplerate: 48000 hz, samples per channel: 485603, duration: 10 sec
encoded01.qoa: size: 383 kb (392304 bytes) = 302.95 kbit/s, psnr: 62.69 db
```

In both cases, I hear a click when switching from the first track to the second.

A similar problem exists with Opus codec, for some reason the official developers do not solve it, so someone even came up with a program [OpusGap](https://github.com/Octocontrabass/opusgap).

**Comment by braheezy** [comment]
I can look at improving the runtime feedback and binary size. 

As far as the clicks go, I don't really know anything useful about audio. But I'm willing to learn! I will need time to research.

Is gapless playback a feature implemented in audio players? Or must it be solved at the specification level i.e., upstream?

**Comment by sergeevabc** [comment]
Thank you for your willingness to make changes, @braheezy. I understand your confusion in the face of the unknown, because I am a regular user myself. not a developer. That is why I tried to attract the attention of people who could help us.: @phoboslab is the author of QOA specification and @pfusik is the author of QOA decoder for Foobar2000 player. Gentlemen, please help us.

**Comment by pfusik** [comment]
Comparing only the file sizes is not a good test here. Use `cmp` on macOS and Linux and `fc / b` on Windows to compare the file contents. I checked that, and `encoded01.qoa` is identical to what the [reference encoder](https://github.com/phoboslab/qoa) produces.

This means the problem is not specific to `goqoa`.

My setup:
- HP ZBook Firefly 14
- Windows 11 23H2 x64 with latest updates
- foobar2000 2.1.2 x64
- [foo_qoa 0.3.0](https://www.foobar2000.org/components/view/foo_qoa)

(please share yours!)

I put `encoded01.qoa` and `encoded02.qoa` on the playlist and I do not hear any major click between the files, but I'm using default output settings. How do I switch to "WASAPI Shared without DSP" ?

**Comment by braheezy** [comment]
I added multi-file support to `goqoa play` and when I ran the QOA files from the zip, I didn't hear any clicks and it seemed gapless.

```bash
goqoa play -v Improve\ QOA\ gapless\ playback\ 2024a/*.qoa
DEBU Starting audio File="Improve QOA gapless playback 2024a/encoded01.qoa" SampleRate=44100 ChannelCount=2 BufferedSize=0
DEBU Starting audio File="Improve QOA gapless playback 2024a/encoded02.qoa" SampleRate=44100 ChannelCount=2 BufferedSize=0
```

**Comment by braheezy** [comment]
Closing because I think this is solved in `goqoa` and I haven't heard anything else. Please reopen if you need to.
