### ISSUE TITLE
Proposal: Stop using UPX for Windows builds

### ISSUE THREAD

**Issue by KyodaiKen** [braheezy/goqoa#46]
Hi,

Virus scanners do NOT like UPX.
So I'd like to propose to stop using UPX for the Windows builds.

Thanks.

**Comment by braheezy** [comment]
Hi! The [latest release](https://github.com/braheezy/goqoa/releases/tag/v3.0.0) no longer uses UPX for Windows builds.

I did not know that about the virus scanners so thank you for telling me :)
